[package]
name = "Canvassing-App"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
csv = "1.4.0"
diesel = { version = "2.3.4", features = ["postgres", "chrono"] }
dotenvy = "0.15.7"
openssl = "0.10.75"
pq-sys = "0.7.5"
vcpkg = "0.2.15"
